### ISSUE TITLE
DiceParser not working September 2022

### ISSUE THREAD

**Issue by FoolishNoobish** [Rolisteam/DiceParser#150]
DiceParser is not working on either of the servers I have it installed on. I have removed and reinvited it to both servers and it still is not working.

**Comment by obiwankennedy** [comment]
The slash command version of the bot has been released. This change is required because Discord forces all registered bots to switch to slash commands. 

-If DiceParser stops working on your server. It is probably a permission issue. Please kick, re-invente diceparser from this link: https://discord.com/api/oauth2/authorize?client_id=279722369260453888&permissions=277025429504&scope=applications.commands%20bot

- There is a way to return to using prefix, but we shall ask discord the permission to do so and it is better to have a good reason.  "It was better before it" is not a valid reason.  We must describe features or processes that don't work any more. When we will have a list of feature that can't work anymore. We shall record some video and submit the permission request to discord. Hoping they will accept.
