### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by robinmoussu** [Rolisteam/DiceParser#2]
hi,
I was trying a way to use dungeon and dragon critics (if the dice is 20, then add 10 to the result for example), and during that process, I've found the following command that create a segmentation fault:

    ./dice '8D20+10*@c[=20]'

I am on the commit  7ce5a4af6fb836432eb6ce7637ea09d6a5b4e0bd (used by rolisteam current version).

Since the '@' in not explained in the documentation, I'm not sure of what it does, so I don't know if it is a syntax error, or a anything else.

Furthermore, is there a way to say "make action X if condition C", like "role 6 dices of 20 faces, then add 10 to the result for any 18 or more on the dices".

You can respond either in French or English, as you prefer!

**Comment by obiwankennedy** [comment]
Hi,

Thanks for the report. 
My answer is in English, as you can see :-). 
It may help more people this way.

I add in the documentation of DiceParser (helpMe.md file) to explain the @ operator.
The command segfault because you don't have two result in the execution tree. 

DiceParser builds execution and run it. 
In your example, the execution tree is made of:
Number Node (8) -> DiceRollingNode (D20) -> scalar operator node(+) -> NULL
                                                                           \-> Number Node (8) -> scalar operator node(*) -> NULL

-> Number Node (8) -> scalar operator node(*) -> 
                                        \-> jumping backward @ ->  countingNode (=20)

(Scalar operator has two children the next node and the internal node).

The jumping backward operator tries to reverse browser the tree to find the second dice result. It will not return the first result but the second one. Returning the first previous result the normal behaviour without the @.
So, the command will never work. I will fix the bug to prevent the segfault, but It will display error message. 

____

I plan to implement a if operator, to execution any command if the condition is true.

The command will be 1d20i20{+10}, something like that. 
in {}, it will be possible to add command to modify the result, or to run another command. As in warhammer (v2): 
Assuming 46 is the value of the skill. 

 1d100i[<46]{1d10i10{1d100i[<46]{10+1d10e10}}}

Roll 1d100 if lesser than 46, then roll damage : 1d10.
If the damage roll gives 10, so roll again the skill test to check if the critical is confirmed.
If the critical is confirmed, run 10+1d10e10. It will give the final damage result.
I plan to do something like that.
It will allow combination of several dice, the main technical issue is to know what to display to the user.

**Comment by robinmoussu** [comment]
thanks for the quick fix :)
