### ISSUE TITLE
How  add modifer to total sum in multi instruction?

### ISSUE THREAD

**Issue by frakc** [Rolisteam/DiceParser#27]
Hello, i am looking how to resolve following problem.
player have to roll 2d10+5, on each roll of 10, extra d5 have to be thown and their sum recorded to.
without addition it is pretty simple
```
2d10;$1c[=10];$2d5
# 13,1,5
Details:[2d10;$1c[=10];$2d5 (10 3 - 5)]
```
I want to add extra +5 to sum of 2d10
!2d10+5;$1c[=10];$2d5
but  bot dos not respond.

**Comment by obiwankennedy** [comment]
The error is on $2d5, as $2 could be 0 and 0d5 leads to error.

The command you want is: 
```
!2d10;$1i.[=10]{+1d5};$2+5;"Final result: $3"
```

The explode operator does not support suboperation. It will be possible soon to do it like this:
```
!2d10e10(1d5)+5
```

**Comment by frakc** [comment]
2d10;$1c[=10];$2d5 this works perfect and count separatrly notmal sum and crit sum.

i want to add +5 on normal sum, not critical sum.  
2d10+5 <- this one  brakes in joined statement !2d10+5;$1c[=10];$2d5

**Comment by frakc** [comment]
thank you now formula works properly
!2d10;$1c[=10];$2i:[>0]{$2d5};$1+4;"normal damage $4, critical damage $3"


however there is still  problem with adding + bonus to first  case.  (in example above i just moved that operation to sepparate case)
!2d10+4;$1c[=10];$2i:[>0]{$2d5};$1+0;"normal damage $4, critical damage $3"
here $3 is always 0  even if 2d10 both 10

**Comment by obiwankennedy** [comment]
it is because this can't worked: `2d10+4;$1c[=10]`

in diceparser, each instruction has a result.
Diceparser manages 3 types of result: dicelist, number and string
The result type of: 2d10 is dicelist.
The result type of: 2d10+4 is number (assuming you want to roll 2 dice, sum their values and add 4. 

Count operator (c) works on dicelist only. If previous result isn't dicelist, it does nothing.

**Comment by frakc** [comment]
got it, thanks
