### ISSUE TITLE
Macros working only 50% of the time

### ISSUE THREAD

**Issue by mprangenberg** [Rolisteam/DiceParser#73]
I have several regex-macros with lists on Discord. And last week they worked like a charm. Today they only sometimes give a result and sometimes they just don't do anything. Is there a known issue? Is the bot maybe just overworked?

These are the affected macros:
id: 3 Pattern: ([0-9]*)[f,F]ertigkeit Command: "
Fertigkeitswürfel:
";\1L[1,2,3,4,5,⚔️] Regexp: True

id: 4 Pattern: ([0-9]*)[w,W]affe Command: "
Waffen-/Ausrüstungswürfel:
";\1L[💀,2,3,4,5,⚔️] Regexp: True

id: 5 Pattern: ([0-9]*)[a,A]rtefakt8 Command: "
8-seitiger Artefaktwürfel:
";\1L[1,2,3,4,5,⚔️,⚔️,⚔️⚔️] Regexp: True

id: 6 Pattern: ([0-9]*)[a,A]rtefakt10 Command: "
10-seitiger Artefaktwürfel:
";\1L[1,2,3,4,5,⚔️,⚔️,⚔️⚔️,⚔️⚔️,⚔️⚔️⚔️] Regexp: True

id: 7 Pattern: ([0-9]*)[a,A]rtefakt12 Command: "
12-seitiger Artefaktwürfel:
";\1L[1,2,3,4,5,⚔️,⚔️,⚔️⚔️,⚔️⚔️,⚔️⚔️⚔️,⚔️⚔️⚔️,⚔️⚔️⚔️⚔️] Regexp: True

id: 8 Pattern: ([0-9]*)[a,A]ttribut Command: "
Attributswürfel:
";\1L[💀,2,3,4,5,⚔️] Regexp: True

id: 9 Pattern: ([0-9]*)[b,B]asis(?!*) Command: "
Basiswürfel:
";\1L[💀,2,3,4,5,⚔️] Regexp: True

**Comment by SaltatorMortis** [comment]
nah the regfu wasnt that bad :-)

found another string related but by trying:
`!"string"+"before";$1;$2;$3;"second";$4+"try"`
`before ; string ; second ; try ; second`

**Comment by obiwankennedy** [comment]
I change the behaviour of the L operator in order to make it more generic. 
You have an issue because you have number and not number in the same list of value. 
Now number in list result are treated as number result so you can add value (+19) or use other operator. But in your case, it should work with normal value but the emoji break the thing or the opposite, I guess.
I will fix it.

**Comment by mprangenberg** [comment]
Thanks for the help. I've now made it all emojis and it works great.
