### ISSUE TITLE
Check on result + bonus

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/DiceParser#86]
Hello,
Let me explain :

I wanted to implement an automatic roll in a character sheet (french rpg called oreste).

The system for a skill check is to roll ( characteristic1+charateristic2 + skill ) D10
Test each dice roll vs a success check.
And finally vs a difficulty check.

I wanted to only implement the first check.

so it is a roll vs a check value, no big deal there is the **_c[>]_** for that ...

Not that easy ...

**I found no way to alterate each roll result by the bonus before the check test.**

What I tried :

**!(5d10+3)c[>=7]** 

the bot answer is : **_got at your dice roll [(5d10+3)c[>=7]]_**

**!5d10+3c[>=7]** 

the bot answer is : **_got at your dice roll [5d10+3c[>=7]]_**

i even tried to substract the bonus to the check value : !5d10c[>=(7-3)] 
=> no display in return.

I even tried to go with the write usage given in the documentation... i opened an other issue for that.

Please help

**Comment by obiwankennedy** [comment]
Yes, it is normal.

The result of 5d10+3 is number, because of the +3.
Let says you rolled [2,7,9,5,1] => then diceparser add 3 => so the result becomes 27 then you asks to compare with 7 with the `Count` operator. 
The count operator needs a dice result as previous node. It can't work on number value.

The command you want to roll is this:

`5d[4-13]c[>=7]`

on recent version of diceparser it may be: (the 1.9.3 will have this syntax I think)
`5d[4..13]c[>=7]`
